find: port to Ubuntu 20.04 cross-compiling for OpenWRT 21.02
In the above build environment, HAVE_ENDPWENT seems to be defined to 0
instead of being #undef'ed.  Hence the build fails:

  parser.c: In function 'parse_user':
  parser.c:75:20: error: expected expression before ')' token
     75 | # define endpwent ()
        |                    ^
  parser.c:2463:7: note: in expansion of macro 'endpwent'
   2463 |       endpwent ();
        |       ^~~~~~~~

* find/parser.c (HAVE_ENDGRENT,HAVE_ENDPWENT): Change from #ifndef to
"#if !", and define the replacement code to "(void) 0".

Fixes https://github.com/openwrt/packages/issues/17912

(cherry picked from commit fa7e628e19c75a3650b9010a37f3388758245b68)